'use strict';
const ENDPOINT='https://oespoljjeslpsnhjwsra.supabase.co/functions/v1/spark-ai';
const STORAGE='spark-os-stable-v2';
const LEGACY_STORAGE='spark-os-stable-v1';
const TYPE_LABELS={auto:'Otomatik',idea:'Fikir',problem:'Problem',observation:'Gözlem',question:'Soru',opportunity:'Fırsat',habit:'Alışkanlık'};
let state=loadState();let selectedIdeaId=null;let captureType='auto';
function uid(){return(globalThis.crypto&&crypto.randomUUID)?crypto.randomUUID():'s-'+Date.now()+'-'+Math.random().toString(16).slice(2)}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function now(){return new Date().toISOString()}
function emptyState(){return{version:2,ideas:[],experiments:[],learnings:[],activeExperimentId:null}}
function normalizeState(raw){const s=raw&&typeof raw==='object'?raw:emptyState();s.version=2;s.ideas=Array.isArray(s.ideas)?s.ideas:[];s.experiments=Array.isArray(s.experiments)?s.experiments:[];s.learnings=Array.isArray(s.learnings)?s.learnings:[];s.ideas=s.ideas.filter(x=>x&&x.id&&x.text).map(x=>({id:String(x.id),text:String(x.text),context:String(x.context||''),createdAt:x.createdAt||now(),selectedType:TYPE_LABELS[x.selectedType]?x.selectedType:'auto',status:['captured','analyzed','active','learned','failed','clarify'].includes(x.status)?x.status:'captured',analysis:x.analysis&&typeof x.analysis==='object'?x.analysis:null,error:x.error||null}));s.experiments=s.experiments.filter(x=>x&&x.id&&x.ideaId).map(x=>({id:String(x.id),ideaId:String(x.ideaId),startedAt:x.startedAt||now(),days:Array.isArray(x.days)?x.days.filter(d=>d&&d.date).map(d=>({date:String(d.date),doneAt:d.doneAt||now(),note:String(d.note||''),score:Number(d.score)||0})):[],completedAt:x.completedAt||null,abandonedAt:x.abandonedAt||null,learning:String(x.learning||'')}));const active=s.experiments.find(x=>x.id===s.activeExperimentId&&!x.completedAt&&!x.abandonedAt);s.activeExperimentId=active?active.id:null;return s}
function loadState(){let raw=null;try{raw=JSON.parse(localStorage.getItem(STORAGE)||'null')}catch{}if(!raw){try{raw=JSON.parse(localStorage.getItem(LEGACY_STORAGE)||'null')}catch{}}return normalizeState(raw)}
function save(){try{localStorage.setItem(STORAGE,JSON.stringify(state))}catch{}renderAll()}
function toast(msg){const el=document.getElementById('toast');el.textContent=msg;el.classList.add('show');clearTimeout(window.__t);window.__t=setTimeout(()=>el.classList.remove('show'),1900)}
function getIdea(id){return state.ideas.find(x=>x.id===id)||null}
function getActiveExperiment(){return state.experiments.find(x=>x.id===state.activeExperimentId&&!x.completedAt&&!x.abandonedAt)||null}
function dayKey(){return new Date().toLocaleDateString('en-CA')}
function humanError(code,message){if(message)return message;return({AI_NOT_CONFIGURED:'AI anahtarı yapılandırılmamış.',RATE_LIMITED:'Çok fazla istek gönderildi. Biraz sonra tekrar dene.',AI_PROVIDER_ERROR:'AI sağlayıcısı şu anda yanıt veremiyor.',AI_UNAVAILABLE:'AI bağlantısı zaman aşımına uğradı.',AI_SCHEMA_MISMATCH:'AI cevabı beklenen yapıda değildi.'}[code]||'AI analizi tamamlanamadı.')}
function priorityScore(idea){const p=idea?.analysis?.priority;if(!p)return null;const impact=Math.max(1,Math.min(5,Number(p.impact)||3)),learning=Math.max(1,Math.min(5,Number(p.learning)||3)),effort=Math.max(1,Math.min(5,Number(p.effort)||3));const raw=impact*2+learning*2+(6-effort);return Math.max(0,Math.min(100,Math.round(((raw-5)/20)*100)))}
function priorityLabel(score){if(score==null)return'Analiz bekliyor';if(score>=75)return'Öncelikli';if(score>=50)return'Değerli test';return'Bekleyebilir'}
function statusLabel(status){return({captured:'Analiz bekliyor',analyzed:'Analiz hazır',clarify:'Açıklama gerekiyor',active:'Aktif deney',learned:'Öğrenildi',failed:'AI hatası'}[status]||status)}
function statusClass(status){return status==='failed'?'error':status==='clarify'?'warn':status==='active'?'accent':''}
function sortIdeas(list){return [...list].sort((a,b)=>{const sa=priorityScore(a),sb=priorityScore(b);if(sa!=null||sb!=null)return(sb??-1)-(sa??-1)||new Date(b.createdAt)-new Date(a.createdAt);return new Date(b.createdAt)-new Date(a.createdAt)})}
function go(name){['today','capture','ideas','learn'].forEach(v=>document.getElementById(v+'View').classList.toggle('active',v===name));document.querySelectorAll('.nav button[data-go]').forEach(b=>b.classList.toggle('active',b.dataset.go===name));if(name==='capture')setTimeout(()=>document.getElementById('captureText').focus(),30);renderAll();window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('.nav button[data-go]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.go)));
document.getElementById('typeChips').addEventListener('click',e=>{const btn=e.target.closest('[data-type]');if(!btn)return;captureType=btn.dataset.type;document.querySelectorAll('.type-chip').forEach(x=>x.classList.toggle('active',x===btn))});
async function callAI(idea,extraContext=''){const typeContext=idea.selectedType&&idea.selectedType!=='auto'?`Kullanıcı kayıt türünü ${TYPE_LABELS[idea.selectedType]} olarak seçti.`:'';const context=[typeContext,idea.context,extraContext].filter(Boolean).join('\n\n').slice(0,1200);const res=await fetch(ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({capture:idea.text,context})});const body=await res.json().catch(()=>({}));if(!res.ok){const e=new Error(humanError(body.error,body.message));e.code=body.error;throw e}if(!body.analysis||typeof body.analysis!=='object')throw new Error('AI geçerli bir analiz döndürmedi.');return body.analysis}
async function analyzeIdea(id,extraContext=''){const idea=getIdea(id);if(!idea)return;selectedIdeaId=id;setCaptureMessage('AI analiz ediyor…','warn');setAnalyzeBusy(true);try{const analysis=await callAI(idea,extraContext);idea.analysis=analysis;idea.error=null;idea.status=analysis.clarification?'clarify':'analyzed';save();showAnalysis(id)}catch(e){idea.status='failed';idea.error=e instanceof Error?e.message:'AI analizi tamamlanamadı.';save();showAnalysis(id)}finally{setAnalyzeBusy(false);setCaptureMessage('','')}}
function setAnalyzeBusy(b){const btn=document.getElementById('analyzeBtn');btn.disabled=b;btn.textContent=b?'Analiz ediliyor…':'AI ile analiz et →'}
function setCaptureMessage(msg,type){document.getElementById('captureMessage').innerHTML=msg?`<div class="status ${type}">${esc(msg)}</div>`:''}
document.getElementById('captureForm').addEventListener('submit',async e=>{e.preventDefault();const text=document.getElementById('captureText').value.trim();const context=document.getElementById('captureContext').value.trim();if(text.length<4){setCaptureMessage('Biraz daha açık yaz.','error');return}const idea={id:uid(),text,context,selectedType:captureType,createdAt:now(),status:'captured',analysis:null,error:null};state.ideas.unshift(idea);save();selectedIdeaId=idea.id;document.getElementById('captureText').value='';document.getElementById('captureContext').value='';captureType='auto';document.querySelectorAll('.type-chip').forEach(x=>x.classList.toggle('active',x.dataset.type==='auto'));await analyzeIdea(idea.id)});
function showAnalysis(id){selectedIdeaId=id;const idea=getIdea(id);const panel=document.getElementById('analysisPanel');if(!idea)return;panel.classList.add('open');if(idea.status==='failed'){panel.innerHTML=`<div class="status error"><b>Analiz yapılamadı.</b><br>${esc(idea.error||'Bilinmeyen hata')}</div><div class="row" style="margin-top:12px"><button class="btn primary" onclick="analyzeIdea('${idea.id}')">AI ile tekrar dene</button><button class="btn soft" onclick="go('ideas')">Kayıtlı fikri gör</button></div>`;return}const a=idea.analysis;if(!a){panel.innerHTML='<div class="status warn">Bu fikir henüz analiz edilmedi.</div><button class="btn primary" style="margin-top:10px" onclick="analyzeIdea(\''+idea.id+'\')">Şimdi analiz et</button>';return}const active=getActiveExperiment();const blocked=active&&active.ideaId!==idea.id;const score=priorityScore(idea);panel.innerHTML=`${a.clarification?`<div class="clarify"><b>AI bir şeyi netleştirmek istiyor:</b><p>${esc(a.clarification)}</p><input id="clarifyInput" class="inline-input" maxlength="500" placeholder="Kısa cevabın"><div class="row" style="margin-top:8px"><button class="btn primary" onclick="submitClarification('${idea.id}')">Cevabı gönder</button></div></div>`:'<div class="status ok">Bu analiz bir hipotezdir; amaç hızlıca test etmektir.</div>'}<div class="analysis-grid" style="margin-top:12px"><div class="analysis-block full"><div class="row between"><div><small>YENİDEN ÇERÇEVELE</small><strong>${esc(a.reframe||idea.text)}</strong></div>${score!=null?`<div class="priority"><div class="priority-score">${score}</div><div class="priority-text"><b>${priorityLabel(score)}</b><span>öncelik puanı</span></div></div>`:''}</div><p class="tiny muted">${esc(a.why_it_matters||'')}</p></div><div class="analysis-block"><small>HİPOTEZ</small><strong>${esc(a.hypothesis||'')}</strong></div><div class="analysis-block"><small>10 DAKİKALIK İLK ADIM</small><strong>${esc(a.first_step?.title||'')}</strong></div><div class="analysis-block"><small>3 GÜNLÜK DENEY</small><strong>${esc(a.experiment?.action||'')}</strong></div><div class="analysis-block"><small>BAŞARI ÖLÇÜTÜ</small><strong>${esc(a.experiment?.success_metric||'')}</strong></div><div class="analysis-block full"><small>ÖNCELİK SİNYALLERİ</small><div class="row"><span class="pill">Etki ${Number(a.priority?.impact)||3}/5</span><span class="pill">Efor ${Number(a.priority?.effort)||3}/5</span><span class="pill">Öğrenme ${Number(a.priority?.learning)||3}/5</span></div><p class="tiny muted">${esc(a.priority?.reason||'')}</p></div></div>${blocked?`<div class="status warn" style="margin-top:12px">Zaten aktif bir deneyin var. Yeni deneyi başlatmadan önce onu bitir veya bırak.</div>`:''}<div class="row" style="margin-top:12px"><button class="btn accent" ${a.clarification||blocked?'disabled':''} onclick="startExperiment('${idea.id}')">Bugünün deneyi yap</button><button class="btn soft" onclick="go('ideas')">Şimdilik beklesin</button></div>`}
async function submitClarification(id){const input=document.getElementById('clarifyInput');const answer=input?input.value.trim():'';if(answer.length<2){toast('Kısa bir cevap yaz.');return}await analyzeIdea(id,'AI açıklama sorusuna kullanıcının cevabı: '+answer)}
function startExperiment(ideaId){const idea=getIdea(ideaId);if(!idea||!idea.analysis||idea.analysis.clarification)return;const active=getActiveExperiment();if(active&&active.ideaId!==ideaId){toast('Önce mevcut deneyi bitir veya bırak.');go('today');return}if(active&&active.ideaId===ideaId){go('today');return}const e={id:uid(),ideaId,startedAt:now(),days:[],completedAt:null,abandonedAt:null,learning:''};state.experiments.unshift(e);state.activeExperimentId=e.id;idea.status='active';save();go('today');toast('Deney başladı.')}
function completeToday(){const e=getActiveExperiment();if(!e)return;const key=dayKey();if(e.days.some(d=>d.date===key)){toast('Bugün zaten kaydedildi.');return}const note=document.getElementById('dailyNote')?.value.trim()||'';const score=Number(document.getElementById('dailyScore')?.value||0);e.days.push({date:key,doneAt:now(),note:note.slice(0,500),score:score>=1&&score<=5?score:0});save();toast('Bugünkü deney kaydedildi.')}
function toggleAbandon(){document.getElementById('abandonConfirm')?.classList.toggle('open')}
function abandonExperiment(){const e=getActiveExperiment();if(!e)return;e.abandonedAt=now();const idea=getIdea(e.ideaId);if(idea)idea.status=idea.analysis?'analyzed':'captured';state.activeExperimentId=null;save();toast('Deney bırakıldı; fikir havuzuna döndü.')}
function finishExperiment(){const e=getActiveExperiment();if(!e)return;const note=document.getElementById('learningNote')?.value.trim()||'';if(note.length<3){toast('Bir cümleyle ne öğrendiğini yaz.');return}e.completedAt=now();e.learning=note;state.activeExperimentId=null;const idea=getIdea(e.ideaId);if(idea)idea.status='learned';state.learnings.unshift({id:uid(),experimentId:e.id,ideaId:e.ideaId,text:note,createdAt:e.completedAt,daysCompleted:e.days.length,averageScore:averageScore(e.days)});save();go('learn');toast('Öğrenme kaydedildi.')}
function averageScore(days){const scores=days.map(d=>Number(d.score)||0).filter(Boolean);if(!scores.length)return 0;return Math.round((scores.reduce((a,b)=>a+b,0)/scores.length)*10)/10}
